# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: zendesk_api
output: zendesk_client.gen.go
generate:
  client: true
  models: true
output-options:
  response-type-suffix: Wrap
